- emcee/ensemble.py
- emcee/mh.py
Fixed the calls to `integrated_time` in MH and Ensemble samplers.
This fixes #186 and #187
> Fix calls of integrated_time

- docs/user/advanced.rst
Added progress bar example (for clint) to docs in response to #163.
> Updated docs with progress bar example.

- emcee/mpi_pool.py
We have a downstream user with a broken MPI installation, which crashes on importing mpi4py. She also can't use emcee in serial mode, because the mpi_pool module tries importing mpi4py.MPI.
This change fixes that (certainly rare) issue by moving the mpi4py import to inside the MPIPool initialization.
> Move import of mpi4py to inside MPIPool initialization

- emcee/ptsampler.py
Noticed this wasn't quite accurate, as it will run if nwalkers = 2*dims.
> Minor assertion message change

- emcee/mh.py
- emcee/ptsampler.py
- emcee/sampler.py
- emcee/tests.py
The generic Sampler.run_mcmc() function wouldn't work right for PTSampler
because it passed the RNG state, `rstate0`, as the second positional argument
to sample(), while for PTSampler the second positional argument was the extra
`lnlike0` parameter. If you tried to pass `lnlike0` yourself, then, you'd
get an exception for a doubly-specified keyword.
Anyway, the best solution is probably to pass `rstate0` as a keyword argument so
that subclasses can have differently-ordered arguments if they want. Do that.
This also requires fixing a discrepancy between the documentation and
implemention of the M-H sampler, which claimed the RNG state keyword was
`rstate0` when it was really being called `randomstate`.
> Fix PTSampler.run_mcmc()

- .travis.yml
I'm having troubles building a python3.6 conda package for emcee, so there may be some compatibility issues. Anyway, it's always useful to test with the latest and greatest....
This is the one I've run into (it's quite possible being upstream, but maybe it can be worked around here): https://ci.appveyor.com/project/Astropy/conda-channel-astropy/build/1.0.447/job/10c7wn6nith6vb4c#L1106
> Adding python 3.6 to the travis matrix

- .gitattributes
The current language statistics are taking in account the `document`
folder. This shows the project as only ~43% Python... The `.gitattributes`
file fixes this by excluding that folder and additionally the `Makefile` in
the root folder as well.
> Create .gitattributes to fix language statistics

- emcee/autocorr.py
- emcee/tests.py
Hi Dan,
I found a bug that resulted in always-failing multidimensional ACL estimates, even when successive single-dimensional estimates succeed.  Along the way, I noticed that your computation of the ACL is actually O(N^2) because you repeat O(N) computation for each value of the window function; I took the opportunity to fix that, too.
Will
> Autocorrelation fix

- docs/user/advanced.rst
`join` only works on lists of strings, needed to convert floats to strings (via `map`) before performing `join`
> Fix example in "Incrementally Saving" doc

- emcee/ensemble.py
- emcee/tests.py
EnsembleSampler.sample raises an IndexError if `iterations` is not a multiple of `thin`. This PR fixes that and adds a test for the bug.
> MAINT: fixes gh226, gh182

- emcee/ensemble.py
I added the capability to make lnprobfn() call the entire vector p all at once, instead of using map() to iterate over p. For custom lnprobfn() functions that are already highly vectorized, this can bring a large speed-up (for my custom use-case I get over an order of magnitude in speed-up).
> Vectorize lnprobfn call

- emcee/ensemble.py
Minor docstring item here, but it threw me for a loop while experimenting.  I *think* I'm interpreting the beahvior right, aren't I?
> Clarify that vectorize disables pool

- emcee/ensemble.py
The exception that is raised on `initial_state=None` on first run and the comment below still used `pos0`
> Fix wrong argument name in exception

- emcee/ensemble.py
- emcee/pbar.py
This PR enhances the progress bar support to allow use of some of the other `tqdm` progress bars.
Most notably, this enables ``tqdm_notebook``, which I think is much better when working in the notebook environment.  It also allows ``tqdm_gui``, presumably, although I've not tested it.  And if `tqdm` adds more in the future, it should allow that as long as they follow the ``tqdm.tqdm_<something>`` convention for function names.
> Make progress bar optionally use other tqdm pbars

- docs/user/sampler.rst
- emcee/backends/backend.py
- emcee/backends/hdf.py
- emcee/ensemble.py
- emcee/state.py
This closes #264 by adding a docstring for `State`, including it in the docs, and updating the various references to it to hyperlink to the right place.
@dfm you might want to confirm I got everything about `State` right in the new docstring - it's pretty straightforward but I admit I didn't check if anything there of relevance has changed between emcee 2 and 3...
> State docstring

- emcee/ensemble.py
The appveyor failures in #268 piqued my interest even though they were not directly related to that PR.  And it reveals a failure that seems to be due to numpy: it turns out numpy 1.15 (which I can only assume just got picked up by appveyor recently) had a subtle change of behavior: for whatever reason `numpy.squeeze` no longer accepts integer arrays, and that approach is used in processing blobs in `emcee`.  But `squeeze`  seems to behave exactly the same if you just convert the axes argument to tuples...  So this PR just makes that trivial change.
Local testing on 1.15 seemed to do the job.  We shall see what appveyor says, though.
> Fix for numpy 1.15

- emcee/ensemble.py
In Py3.8 importing an ABC from `collections` will result in an Exception. In Py3.7 the behaviour is deprecated. This PR addresses the DeprecationWarning. This PR should be applied to the next `emcee` release, as that will be used extensively on Py3.8.
```
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
```
> MAINT: import from collections.abc

- .travis.yml
This PR adds a py37 entry to the travisCI matrix. Testing py37 is important for finding issues such as that addressed by #283
> CI: include py37 in travisCI matrix

- emcee/moves/red_blue.py
The docstring for `RedBlueMove` does not match the default kwd arg in `__init__`. This PR changes the docstring to reflect reality.
> DOC: randomize_split default True

- docs/index.rst
This should fix the link to testimonials on the first page of the docs.
> Fix link to testimonials

- .travis.yml
- emcee/ensemble.py
- emcee/tests/unit/test_sampler.py
There was a backwards compatibility problem with `lnprobability` (#289). I fixed it doing exactly the same as in `chain`. 
During testing I realized that the `lnprobability` test actually checked it had the wrong shape (emcee3 like), and there was no test for `get_log_prob` shape. Therefore, I added a test for `get_log_prob` shape. And while I was at it, I used `pytest.warns` to capture and check the deprecation warning of the emcee2 methods present in the tests (here I only modified the already present tests, no addition).
Eventually, I replaced the instance of `logging.warn` by `logging.warning`, which is already present and recommended in 2.7 and therefore should not be a problem for anybody.
EDIT: After seeing the results in travis, I set the strings with latex in it to raw strings to …
> Fix #289 and modify some tests

- emcee/ensemble.py
At the beginning of `run_mcmc`, the sampler object tests for linear dependence of the initial state.  This pull request computes the condition number of the covariance matrix of the initial state, and compares against `1e8`.  The previous code computed the determinant of the covariance and compared to zero; that method is sensitive to the *scale* of the parameters (i.e. under re-scaling of parameters `x` to `x_prime = A*x`, the determinant scales as `det(cov(x))` to `det(cov(x_prime)) == A**2*det(cov(x))`.  In a parameter space with small parameters, `det(cov(x))` can be close to zero even when the parameters are quite linearly independent, leading to spurious warnings.
> Scale-invariant Test for Linear Dependence

- docs/_static/notebooks/quickstart.ipynb
It looks to me as if the variable `run` that is referenced in the test, should really be the variable `state`. Maybe the name has been changed in the past without changing the line of text? (Alternatively, I might just not understand what's going on there and where the variable `run` is supposed to come from.)
> Quick start ipynb: Text inconsistent with code cell.

- docs/user/install.rst
Including the repology packaging badge in the installation list. This gives a list of emcee package versions for project distribution (Linux, BSD) in all repositories. It can be useful information for people using those systems.
> Adding packaging badge under installation

- tox.ini
Currently I can't actually run `tox` because my machine only has python3.8 installed. This PR just adds a python3.8 environment to the tox list; all tests pass fine.
> Add python3.8 environment to tox

- src/emcee/backends/hdf.py
- src/emcee/tests/integration/test_longdouble.py
- src/emcee/tests/unit/test_backends.py
Detects whether HDF5 supports long doubles and `xfail`s tests if it doesn't.
Closes #353
> Fix long double test failures with HDF5 and ppc64el

- src/emcee/backends/hdf.py
- src/emcee/tests/unit/test_backends.py
Allow users to enable compression on HDF5 backends.
Compression is applied uniformly to all datasets; one might expect different compression for `accepted` than `chain` or `blobs` but the interface doesn't need additional complications. If `reset` is used on an existing HDF5 file the newly created datasets will have compression enabled or not as specified during backend creation.
Closes #338
> Add HDF5 compression

- src/emcee/backends/backend.py
- src/emcee/backends/hdf.py
- src/emcee/ensemble.py
- src/emcee/tests/unit/test_blobs.py
Reduce the chance of user surprise due to blob dtype inference - strings are object dtypes, object dtypes don't lead to backend weirdness, ragged blob dtypes raise `numpy.VisibleDeprecationWarning` unless `blobs_dtype` is specified. Also fixes problems where `grow` used to re-infer blob dtypes. 
Closes #361
> Solidify blobs dtype inference

- src/emcee/ensemble.py
- src/emcee/tests/unit/test_sampler.py
Added option to use `iterations=None` in [`EnsembleSampler.sample`](https://emcee.readthedocs.io/en/stable/user/sampler/#emcee.EnsembleSampler.sample), as discussed in #369. This produces an infinite stream of samples. Requires `store=False`. Note that tqdm can handle `total=None`. Example:
```python3
import numpy as np
from emcee import EnsembleSampler
def logp(x):
return np.where(((0 <= x) & (x <= 1)).all(-1), 0, -np.inf)
x = np.random.rand(10, 2)
for state in EnsembleSampler(*x.shape, logp).sample(x, progress=True, iterations=None, store=False):
pass
```
> Added infinite iterations option to EnsembleSampler.sample

- src/emcee/backends/backend.py
`np.float` is deprecated as of numpy 1.20. https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations.
> Fix np.float deprecation

- src/emcee/ensemble.py
- src/emcee/tests/unit/test_ensemble.py
This PR closes #385 by giving support for named parameters in the `EnsembleSampler`.
Specifically this PR:
- allows a user to pass in a list of names (types as `str` but really can be anything) for the parameters to the constructor for `EnsembleSampler`. Checks are made to ensure that the number of unique names are `ndim`
- In the `EnsembleSampler.compute_log_prob` method, these names are used to reshape the parameters passed in to the method (having previously been generated by the `Move`) so that instead of an `ndarray` of shape `(nwalkers, ndim)` it becomes a list of length `nwalkers` of dictionaries of length `ndim`, with each key-value pair being the names and parameters
- A helper function was written to perform the `ndarray` -> `List[Dict[str, np.number]]` conversion, so that it …
> Support for named parameters

- src/emcee/ensemble.py
- src/emcee/pbar.py
`tqdm` allows a description to be given to the progress bar, I find this is helpful in packages where multiple different progress bars are used. This PR allows a description to be added to a `emcee` progress bar based on a string passed to to the `sample` function.
> Added functionality to give a description in the progress bar

- docs/index.rst
Hi,
Relatively new user here, and I've been noticing that the URL to Goodman & Weare (2010) on the front page of the docs is broken. Wanted to help and noticed it's an easy fix, so hopefully this PR points the link to the right place now.
Let me know if there's anything else I should change!
> Update link to Goodman & Weare 2010

- src/emcee/moves/kde.py
Currently, the random generator in the `get_proposal` method for the `KDEMove` is not used when taking samples from the KDE. This is problematic since we cannot run emcee in a reproducible way. This PR fixes this by passing on the random generator to the KDE resampling method, so that sampling is reproducible.
> Pass on random generator to KDE resample method

- docs/user/blobs.rst
Firstly, massive thanks to @dfm for all your efforts with emcee, it is an amazing tool and community and has made a massive difference to my (and I'm sure many others') research. 
Second, thanks to @steven-murray and @lboogaard for your comments in #352. I was also confused by this and your observations were super helpful.
I think this MR will close #352. It is a pretty basic update to the blobs docs to fix a couple of typos and add some more context which I would have found helpful in hindsight and addresses the things brought up in #352 I believe.
> Update blobs docs (#352)

- src/emcee/moves/de.py
- I observed that the current implementation of DEMove, although stated to follow Nelson et al. 2013, does not actually align with the paper's approach. The existing implementation lacked affine-invariance, which is fixed in Nelson's paper.
- There was potential to optimize performance via vectorization.
Changes are only made in the implementation of DEMove in de.py.
- **Alignment with Nelson et al. 2013**:
Fixed the discrepancy between the stated and actual approaches. The normal noise $\epsilon \sim N(0, \sigma^2)$ used to be added to the proposal as per $\gamma_0 (x_i - x_j) + \epsilon$. In this case, $\sigma$ should be tuned for each dimension, which confronts the idea of affine-invariance. Now it defines the distribution over gamma: $\gamma = \gamma_0 (1 + \epsilon)$, which follows …
> Fixed DEMove Implementation

- src/emcee/moves/de_snooker.py
- src/emcee/moves/walk.py
This PR addresses #483 for the `WalkMove` and `DESnookerMove` classes by replacing `np.empty` with `np.empty_like`, so the same datatype as the input walker positions is used in new proposals.
> Move proposals should match the dtype of original input

- docs/tutorials/moves.ipynb
This commit fixes a display issue in the class reference, as well as a typo in the same sentence.
> Fix moves documentation typos

- src/emcee/ensemble.py
Fixed a typo in the docstring for the  EnsembleSampler class. Changed "log_pprob_fn" to "log_prob_fn".
> Update EnsembleSampler docstring in ensemble.py

- .github/workflows/tests.yml
- src/emcee/ensemble.py
- src/emcee/tests/unit/test_ensemble.py
- tox.ini
Starts to address #509 
- bumps the Python versions being tested to a minimum of cp39. This might have a mixed reception...
- makes a GHA entry for testing with numpy>=2.0.0rc1
- changes the usage of `np.VisibleDeprecationWarning` to `np.exceptions.VisibleDeprecationWarning`.
> MAINT: updates for numpy2 closes #509
